"""
render_supp1_flex_filter_umap.py — Fig 3 Supp 1, Panel 1c.

Per-patient filter-status UMAP. For each of the 4 FLEX patients, a UMAP
shows the patient's cells in a patient-local 2D manifold (computed from
their subset of the cohort scVI 50-dim latent), colored by which step of
preprocessing (if any) removed them.

The patient-local UMAP is generated by the one-off
`coordination/scripts/make_per_patient_umaps.py` (Path B per
CP_supp1_1c_per_patient_embeddings.md) — the cohort scVI latent already
contains within-patient sample-batch correction, so re-projecting per
patient gives a faithful patient-merged view without retraining scVI.

Visual structure: 2×2 patient grid. Each sub-panel shows:
    kept              — passes all filters (step_01 → step_15)
    removed_mad       — fails step_02 MAD outlier filter
    removed_doublet   — passes step_02, fails step_03 doublet detection
    removed_manifold  — passes 02+03, fails step_10b manifold artifact
    removed_contam    — passes 02+03+10b, fails step_15 Milo contamination

Note: a patient-local UMAP includes only cells that were in the cohort
latent embedding (step_01 + step_02 + step_03 pass cohort), so MAD/doublet
"removed" cells are NOT present in this view by default. The script handles
this correctly — those cells appear only via 1b's attrition waterfall.

If the per-patient UMAP one-off later includes pre-integration cells
(rebuild via step 06 path), this script will pick them up automatically
from the per-patient CSVs without code changes.

Reviewer question: "Where in each patient's manifold do the post-integration
filters act?"

Inputs (consumes-from-dev / scratch):
    coordination/scratch/per_patient_umap/<patient>_umap.csv
        (cell_id, UMAP_1, UMAP_2)
    Spatial_HBCA/project/01_Preprocessing/outputs/qc_status/
        central_cell_status.csv
        (per-cell step pass flags)

Outputs:
    supp1_flex_filter_umap.pdf
    supp1_flex_filter_umap_data.csv

Pattern source:
    publication/figures/render/joint/render_supp7_1_concord_receipt.py
    (multi-sub-panel patient grid, 1200 DPI rasterized scatter)

Framework conformance: Option B per CP_supp7_python_framework_gap.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT_DEFAULT = SCRIPT_DIR.parents[3]
sys.path.insert(0, str(PROJECT_ROOT_DEFAULT / "publication" / "config"))
from load_aesthetics import (  # noqa: E402
    get_dimensions,
    get_matplotlib_theme,
    get_palette,
    load_aesthetics,
)
from load_paths import load_paths, resolve_path  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("supp1_1c")


SHUFFLE_SEED = 42
STATUS_ORDER = ["kept", "removed_sample_failed_vf",
                "removed_mad", "removed_doublet"]
STATUS_LABELS = {
    "kept": "Kept",
    "removed_sample_failed_vf": "Removed (sample failed VF, step 04)",
    "removed_mad": "Removed (MAD, step 02)",
    "removed_doublet": "Removed (doublet, step 03)",
}
SAMPLE_FAILED_VF = "Pat1_P3_M_UOQ"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--project-root", required=True, type=Path)
    p.add_argument("--out-dir", required=True, type=Path)
    p.add_argument("--umap-dir", type=Path, default=None,
                   help="Per-patient UMAP CSV dir (default: "
                        "coordination/scratch/per_patient_umap/)")
    p.add_argument("--test", action="store_true",
                   help="Subsample 30K cells per patient for sanity render.")
    return p.parse_args()


def attribute_first_fail(df: pd.DataFrame) -> pd.Series:
    """Cell-level attrition: kept / MAD-failed / doublet-failed.

    At the per-patient pre-integration stage, only cell-level QC filters
    (step_02 MAD, step_03 doublet) are operating. Manifold and contamination
    filters (steps 10b, 15) are downstream of integration and lack context
    here — cells failing those still attribute to `kept` since they passed
    cell-level QC.
    """
    n = len(df)
    out = np.full(n, "kept", dtype=object)
    mad_fail = ~df["step_02_mad_pass"].astype("boolean").fillna(False).to_numpy()
    doublet_fail = ~df["step_03_doublet_pass"].astype("boolean").fillna(False).to_numpy()
    s02_pass = df["step_02_mad_pass"].astype("boolean").fillna(False).to_numpy()
    sample_failed_vf = ((df["sample_id"] == SAMPLE_FAILED_VF).to_numpy()
                       & s02_pass)
    out[doublet_fail] = "removed_doublet"
    out[mad_fail] = "removed_mad"
    out[sample_failed_vf] = "removed_sample_failed_vf"
    return pd.Series(out, index=df.index, name="status")


def get_status_palette(config: dict) -> dict:
    """Cell-level attrition palette via qc_status (matches Panel 1a)."""
    qc = get_palette("qc_status", config)
    return {
        "kept": qc["kept"],
        "removed_sample_failed_vf": qc["removed_sample_failed_vf"],
        "removed_mad": qc["removed_initial"],
        "removed_doublet": qc["removed_doublet"],
    }


def render(per_patient: dict[str, pd.DataFrame], status_pal: dict,
           dims: dict, out_pdf: Path) -> None:
    patients = sorted(per_patient.keys())
    n_pat = len(patients)
    n_cols = 2
    n_rows = int(np.ceil(n_pat / n_cols))
    fig_w = dims["width"] * n_cols
    fig_h = dims["height"] * n_rows
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(fig_w, fig_h))
    axes = np.atleast_2d(axes).flatten()

    rng = np.random.default_rng(SHUFFLE_SEED)

    for ax, pat in zip(axes, patients):
        df = per_patient[pat]
        perm = rng.permutation(len(df))
        df_shuf = df.iloc[perm].reset_index(drop=True)
        c = df_shuf["status"].map(status_pal).to_numpy()
        ax.scatter(df_shuf["UMAP_1"], df_shuf["UMAP_2"], c=c,
                   s=0.5, linewidths=0, alpha=0.4, rasterized=True)
        ax.set_title(f"{pat}", fontsize=7, loc="left", pad=2)
        ax.set_aspect("equal")
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(False)

    for j in range(n_pat, len(axes)):
        axes[j].set_visible(False)

    handles = [
        Line2D([0], [0], marker="o", color="w",
               markerfacecolor=status_pal[s], markersize=4,
               label=STATUS_LABELS[s])
        for s in STATUS_ORDER
    ]
    fig.legend(handles=handles, loc="lower center", ncol=5,
               bbox_to_anchor=(0.5, -0.01), frameon=False, fontsize=6)

    fig.tight_layout(rect=(0, 0.03, 1, 1))
    fig.savefig(out_pdf, format="pdf", dpi=1200, bbox_inches="tight")
    log.info("Wrote %s", out_pdf)


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    paths = load_paths(config_dir=str(args.project_root / "publication" / "config"))
    tracker_path = Path(resolve_path("flex_central_cell_status", paths))

    umap_dir = args.umap_dir or Path(resolve_path("flex_per_patient_umap_dir", paths))
    umap_csvs = sorted(f for f in umap_dir.glob("*_umap.csv")
                       if not f.name.startswith("._"))
    if not umap_csvs:
        raise FileNotFoundError(f"No per-patient UMAP CSVs in {umap_dir}")

    log.info("Reading master tracker: %s", tracker_path)
    tracker = pd.read_csv(
        tracker_path, low_memory=False,
        usecols=["cell_id", "sample_id", "step_02_mad_pass",
                 "step_03_doublet_pass"]
    ).set_index("cell_id")
    log.info("Tracker: %d cells", len(tracker))

    per_patient: dict[str, pd.DataFrame] = {}
    all_rows: list[pd.DataFrame] = []
    for f in umap_csvs:
        pat = f.stem.replace("_umap", "")
        umap = pd.read_csv(f, index_col=0)
        umap.index.name = "cell_id"
        df = umap.join(tracker, how="inner").reset_index()
        df["status"] = attribute_first_fail(df)
        df["patient_id"] = pat
        if args.test and len(df) > 30_000:
            df = df.sample(n=30_000, random_state=SHUFFLE_SEED).reset_index(drop=True)
        log.info("[%s] %d cells; status: %s", pat, len(df),
                 df["status"].value_counts().to_dict())
        per_patient[pat] = df
        all_rows.append(df[["cell_id", "patient_id", "UMAP_1", "UMAP_2", "status"]])

    aes = load_aesthetics()
    plt.rcParams.update(get_matplotlib_theme(aes))
    status_pal = get_status_palette(aes)
    dims = get_dimensions("umap", aes)

    out_pdf = args.out_dir / "supp1_flex_filter_umap.pdf"
    out_csv = args.out_dir / "supp1_flex_filter_umap_data.csv"

    render(per_patient, status_pal, dims, out_pdf)

    pd.concat(all_rows, ignore_index=True).to_csv(out_csv, index=False)
    log.info("Wrote %s", out_csv)


if __name__ == "__main__":
    main()
